import { User, Demand } from './types'

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ana Diretora',
    email: 'ana@demandflow.com',
    password: '123456',
    role: 'director',
    microsoftId: 'ms-ana-001',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
  },
  {
    id: 'u2',
    name: 'Carlos Gerente',
    email: 'carlos@demandflow.com',
    password: '123456',
    role: 'manager',
    managerId: 'u1',
    microsoftId: 'ms-carlos-002',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
  {
    id: 'u3',
    name: 'Beatriz Analista',
    email: 'beatriz@demandflow.com',
    password: '123456',
    role: 'analyst',
    managerId: 'u2',
    microsoftId: 'ms-beatriz-003',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
  },
  {
    id: 'u4',
    name: 'Diego Analista',
    email: 'diego@demandflow.com',
    password: '123456',
    role: 'analyst',
    managerId: 'u2',
    microsoftId: 'ms-diego-004',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
  },
  {
    id: 'u5',
    name: 'Eduardo Gerente',
    email: 'eduardo@demandflow.com',
    password: '123456',
    role: 'manager',
    managerId: 'u1',
    microsoftId: 'ms-eduardo-005',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=5',
  },
  {
    id: 'u6',
    name: 'Fernanda Analista',
    email: 'fernanda@demandflow.com',
    password: '123456',
    role: 'analyst',
    managerId: 'u5',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=6',
  },
  {
    id: 'u7',
    name: 'Gabriel Admin',
    email: 'gabriel@demandflow.com',
    password: '123456',
    role: 'admin',
    managerId: 'u1',
    microsoftId: 'ms-gabriel-007',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=7',
  },
]

export const MOCK_DEMANDS: Demand[] = [
  {
    id: 'd1',
    title: 'Relatório Financeiro Q3',
    description: 'Consolidar dados do trimestre',
    status: 'em-andamento',
    priority: 'high',
    dueDate: '2024-10-25',
    assigneeId: 'u3',
    createdAt: '2024-10-20',
    comments: [
      {
        id: 'c1',
        demandId: 'd1',
        authorId: 'u2',
        authorName: 'Carlos Gerente',
        text: 'Priorizar esta demanda nesta semana.',
        timestamp: '2024-10-21T10:00:00Z',
      },
    ],
  },
  {
    id: 'd2',
    title: 'Aprovação de Orçamento',
    description: 'Revisar orçamento da campanha',
    status: 'nao-iniciado',
    priority: 'high',
    dueDate: '2024-10-26',
    assigneeId: 'u2',
    createdAt: '2024-10-21',
    comments: [
      {
        id: 'c2',
        demandId: 'd2',
        authorId: 'u1',
        authorName: 'Ana Diretora',
        text: 'Preciso disso até sexta.',
        timestamp: '2024-10-22T14:00:00Z',
      },
    ],
  },
  {
    id: 'd3',
    title: 'Atualizar Apresentação',
    description: 'Slides para a reunião geral',
    status: 'concluido',
    priority: 'medium',
    dueDate: '2024-10-22',
    assigneeId: 'u4',
    createdAt: '2024-10-18',
  },
  {
    id: 'd4',
    title: 'Planejamento Estratégico',
    description: 'Definir metas para o próximo ano',
    status: 'aguardando',
    priority: 'high',
    dueDate: '2024-10-30',
    assigneeId: 'u1',
    createdAt: '2024-10-15',
  },
  {
    id: 'd5',
    title: 'Análise de Concorrentes',
    description: 'Levantamento de novas features',
    status: 'nao-iniciado',
    priority: 'low',
    dueDate: '2024-10-28',
    assigneeId: 'u3',
    createdAt: '2024-10-23',
  },
  {
    id: 'd6',
    title: 'Revisão de Contratos',
    description: 'Verificar cláusulas de renovação',
    status: 'em-andamento',
    priority: 'medium',
    dueDate: '2024-10-27',
    assigneeId: 'u4',
    createdAt: '2024-10-19',
  },
  {
    id: 'd7',
    title: 'Campanha de Marketing Q4',
    description: 'Planejar campanhas para o final de ano',
    status: 'cancelado',
    priority: 'low',
    dueDate: '2024-10-20',
    assigneeId: 'u2',
    createdAt: '2024-10-10',
  },
  {
    id: 'd8',
    title: 'Auditoria Interna',
    description: 'Revisar processos e conformidade',
    status: 'aguardando',
    priority: 'high',
    dueDate: '2024-10-29',
    assigneeId: 'u4',
    createdAt: '2024-10-17',
  },
  {
    id: 'd9',
    title: 'Onboarding de Novos Analistas',
    description: 'Preparar materiais e treinamentos',
    status: 'em-andamento',
    priority: 'medium',
    dueDate: '2024-11-05',
    assigneeId: 'u5',
    createdAt: '2024-10-24',
  },
  {
    id: 'd10',
    title: 'Relatório de Vendas Mensal',
    description: 'Compilar dados de vendas de outubro',
    status: 'nao-iniciado',
    priority: 'high',
    dueDate: '2024-11-02',
    assigneeId: 'u6',
    createdAt: '2024-10-25',
  },
]
